module pl.edziennik.client {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.base;
    requires lombok;
    requires java.logging;
    requires spring.core;
    requires spring.web;
    requires spring.webmvc;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires org.apache.httpcomponents.client5.httpclient5;
    requires com.fasterxml.jackson.datatype.jdk8;
    requires com.fasterxml.jackson.datatype.jsr310;


    exports pl.edziennik.client;
    exports pl.edziennik.client.controller.auth;
    exports pl.edziennik.client.rest;
    exports pl.edziennik.client.controller;
    exports pl.edziennik.client.controller.admin;
    exports pl.edziennik.client.rest.client;
    exports pl.edziennik.client.rest.client.response;
    exports pl.edziennik.client.exception;
    exports pl.edziennik.client.util;
    exports pl.edziennik.client.validator.auth;
    exports pl.edziennik.client.common.model.admin;
    exports pl.edziennik.client.controller.configuration;
    exports pl.edziennik.client.common;
    exports pl.edziennik.client.common.model.student;
    exports pl.edziennik.client.core;
    exports pl.edziennik.client.controller.admin.school;
    exports pl.edziennik.client.controller.admin.account;
    exports pl.edziennik.client.controller.admin.configuration;
    exports pl.edziennik.client.task.register;
    exports pl.edziennik.client.task.school;
    exports pl.edziennik.client.controller.admin.schoolclass;
    exports pl.edziennik.client.core.toast;
    exports pl.edziennik.client.controller.student;
    exports pl.edziennik.client.controller.student.grade;
    opens pl.edziennik.client to javafx.fxml;
    opens pl.edziennik.client.controller.auth to javafx.fxml;
    opens pl.edziennik.client.controller.admin to javafx.fxml;
    opens pl.edziennik.client.controller to javafx.fxml;
    opens pl.edziennik.client.controller.configuration to javafx.fxml;
    opens pl.edziennik.client.controller.admin.school to javafx.fxml;
    opens pl.edziennik.client.task.school to javafx.fxml;
    opens pl.edziennik.client.task.register to javafx.fxml;
    opens pl.edziennik.client.controller.admin.configuration to javafx.fxml;
    opens pl.edziennik.client.controller.admin.account to javafx.fxml;
    opens pl.edziennik.client.core to javafx.fxml;
    exports pl.edziennik.client.controller.admin.account.student;
    opens pl.edziennik.client.controller.admin.account.student to javafx.fxml;
    exports pl.edziennik.client.controller.admin.account.teacher;
    opens pl.edziennik.client.controller.admin.account.teacher to javafx.fxml;
    opens pl.edziennik.client.controller.admin.account.parent to javafx.fxml;
    opens pl.edziennik.client.controller.admin.schoolclass to javafx.fxml;
    opens pl.edziennik.client.controller.student to javafx.fxml;
    opens pl.edziennik.client.controller.student.grade to javafx.fxml;
    opens pl.edziennik.client.controller.teacher to javafx.fxml;
    opens pl.edziennik.client.controller.teacher.subject to javafx.fxml;
    exports pl.edziennik.client.rest.dto.student;
    exports pl.edziennik.client.rest.dto.subject;
    exports pl.edziennik.client.rest.dto.teacher;
    exports pl.edziennik.client.rest.dto.admin;
    exports pl.edziennik.client.rest.dto.school;
    exports pl.edziennik.client.rest.dto.auth;
    exports pl.edziennik.client.rest.dto.schoolclass;
    exports pl.edziennik.client.rest.dto.schoollevel;
    exports pl.edziennik.client.rest.dto.config;
    exports pl.edziennik.client.rest.dto.parent;
    exports pl.edziennik.client.rest.dto;
    exports pl.edziennik.client.controller.admin.account.parent;
    exports pl.edziennik.client.controller.admin.account.admin;
    exports pl.edziennik.client.controller.teacher;
    exports pl.edziennik.client.controller.teacher.subject;
    exports pl.edziennik.client.controller.teacher.grades;
    exports pl.edziennik.client.common.model.teacher;
    opens pl.edziennik.client.controller.admin.account.admin to javafx.fxml;
    opens pl.edziennik.client.common.model.teacher to javafx.fxml;
    opens pl.edziennik.client.rest.dto.grade to com.fasterxml.jackson.annotation;
    opens pl.edziennik.client.controller.teacher.grades to javafx.fxml;
    exports pl.edziennik.client.common.factory;
    exports pl.edziennik.client.common.constants;
    exports pl.edziennik.client.rest.dto.grade;
}